/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/SodaCan.glb -o src/Fiber3d/SodaCan.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function SodaCan(props) {
  const { nodes, materials } = useGLTF('/models/SodaCan.glb')
  const meshRef = useRef(null);

  useFrame(()=>{
    if (!meshRef.current){
        return;
    }

    //meshRef.current.rotation.x += 0.01;
    meshRef.current.rotation.y += 0.01;
  }

);

  return (
    <group {...props} dispose={null}>
      <group scale={13.81} ref={meshRef}>
        <mesh geometry={nodes.sodaCan_1.geometry} material={materials.greyDark} />
        <mesh geometry={nodes.sodaCan_1_1.geometry} material={materials.greyLight} />
        <mesh geometry={nodes.sodaCan_1_2.geometry} material={materials.red} />
        <mesh geometry={nodes.sodaCan_1_3.geometry} material={materials.brownDarkest} />
        <mesh geometry={nodes.sodaCan_1_4.geometry} material={materials.canvasArea} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/SodaCan.glb')
